// Verse of the day. KJV (public domain) — no API, no cost. Curated on-brand for
// TABOR: strength, courage, discipline, faith, brotherhood, perseverance.
// The popup picks one deterministically by the calendar day.

export interface Verse {
  ref: string;
  text: string;
}

export const VERSES: Verse[] = [
  { ref: "Joshua 1:9", text: "Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest." },
  { ref: "Proverbs 27:17", text: "Iron sharpeneth iron; so a man sharpeneth the countenance of his friend." },
  { ref: "1 Corinthians 16:13", text: "Watch ye, stand fast in the faith, quit you like men, be strong." },
  { ref: "Philippians 4:13", text: "I can do all things through Christ which strengtheneth me." },
  { ref: "Isaiah 40:31", text: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles." },
  { ref: "Psalm 18:32", text: "It is God that girdeth me with strength, and maketh my way perfect." },
  { ref: "2 Timothy 1:7", text: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind." },
  { ref: "Romans 8:31", text: "If God be for us, who can be against us?" },
  { ref: "Psalm 23:4", text: "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me." },
  { ref: "1 Corinthians 9:27", text: "But I keep under my body, and bring it into subjection." },
  { ref: "Hebrews 12:1", text: "Let us run with patience the race that is set before us." },
  { ref: "Galatians 6:9", text: "And let us not be weary in well doing: for in due season we shall reap, if we faint not." },
  { ref: "Proverbs 3:5", text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding." },
  { ref: "Matthew 6:33", text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you." },
  { ref: "Psalm 46:1", text: "God is our refuge and strength, a very present help in trouble." },
  { ref: "Ephesians 6:10", text: "Finally, my brethren, be strong in the Lord, and in the power of his might." },
  { ref: "Deuteronomy 31:6", text: "Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee." },
  { ref: "Psalm 27:1", text: "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?" },
  { ref: "Proverbs 18:24", text: "There is a friend that sticketh closer than a brother." },
  { ref: "Ecclesiastes 4:9", text: "Two are better than one; because they have a good reward for their labour." },
  { ref: "Ecclesiastes 4:12", text: "And if one prevail against him, two shall withstand him; and a threefold cord is not quickly broken." },
  { ref: "James 1:12", text: "Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life." },
  { ref: "Romans 5:3-4", text: "Tribulation worketh patience; and patience, experience; and experience, hope." },
  { ref: "1 Peter 5:8", text: "Be sober, be vigilant; because your adversary the devil, as a roaring lion, walketh about, seeking whom he may devour." },
  { ref: "Psalm 144:1", text: "Blessed be the LORD my strength, which teacheth my hands to war, and my fingers to fight." },
  { ref: "Colossians 3:23", text: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men." },
  { ref: "Proverbs 4:23", text: "Keep thy heart with all diligence; for out of it are the issues of life." },
  { ref: "Matthew 5:14", text: "Ye are the light of the world. A city that is set on an hill cannot be hid." },
  { ref: "John 8:12", text: "I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life." },
  { ref: "Psalm 119:105", text: "Thy word is a lamp unto my feet, and a light unto my path." },
  { ref: "Isaiah 41:10", text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee." },
  { ref: "Jeremiah 29:11", text: "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end." },
  { ref: "Romans 12:2", text: "And be not conformed to this world: but be ye transformed by the renewing of your mind." },
  { ref: "Romans 12:1", text: "Present your bodies a living sacrifice, holy, acceptable unto God, which is your reasonable service." },
  { ref: "1 Corinthians 6:19", text: "Know ye not that your body is the temple of the Holy Ghost which is in you?" },
  { ref: "Proverbs 16:3", text: "Commit thy works unto the LORD, and thy thoughts shall be established." },
  { ref: "Psalm 37:5", text: "Commit thy way unto the LORD; trust also in him; and he shall bring it to pass." },
  { ref: "Micah 6:8", text: "What doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?" },
  { ref: "Proverbs 24:16", text: "For a just man falleth seven times, and riseth up again." },
  { ref: "2 Corinthians 12:9", text: "My grace is sufficient for thee: for my strength is made perfect in weakness." },
  { ref: "2 Corinthians 4:8-9", text: "We are troubled on every side, yet not distressed; we are perplexed, but not in despair; cast down, but not destroyed." },
  { ref: "Hebrews 12:11", text: "No chastening for the present seemeth to be joyous, but grievous: nevertheless afterward it yieldeth the peaceable fruit of righteousness." },
  { ref: "Lamentations 3:22-23", text: "It is of the LORD's mercies that we are not consumed, because his compassions fail not. They are new every morning." },
  { ref: "Psalm 5:3", text: "My voice shalt thou hear in the morning, O LORD; in the morning will I direct my prayer unto thee, and will look up." },
  { ref: "Mark 1:35", text: "And in the morning, rising up a great while before day, he went out, and departed into a solitary place, and there prayed." },
  { ref: "Proverbs 13:4", text: "The soul of the sluggard desireth, and hath nothing: but the soul of the diligent shall be made fat." },
  { ref: "Proverbs 21:5", text: "The thoughts of the diligent tend only to plenteousness." },
  { ref: "1 Timothy 4:8", text: "For bodily exercise profiteth little: but godliness is profitable unto all things." },
  { ref: "1 Timothy 6:12", text: "Fight the good fight of faith, lay hold on eternal life, whereunto thou art also called." },
  { ref: "2 Timothy 2:3", text: "Thou therefore endure hardness, as a good soldier of Jesus Christ." },
  { ref: "2 Timothy 4:7", text: "I have fought a good fight, I have finished my course, I have kept the faith." },
  { ref: "Psalm 1:3", text: "And he shall be like a tree planted by the rivers of water, that bringeth forth his fruit in his season." },
  { ref: "Joshua 24:15", text: "As for me and my house, we will serve the LORD." },
  { ref: "Nehemiah 8:10", text: "The joy of the LORD is your strength." },
  { ref: "Psalm 31:24", text: "Be of good courage, and he shall strengthen your heart, all ye that hope in the LORD." },
  { ref: "Psalm 73:26", text: "My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever." },
  { ref: "Isaiah 40:29", text: "He giveth power to the faint; and to them that have no might he increaseth strength." },
  { ref: "Habakkuk 3:19", text: "The LORD God is my strength, and he will make my feet like hinds' feet, and he will make me to walk upon mine high places." },
  { ref: "Zephaniah 3:17", text: "The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy." },
  { ref: "Matthew 11:28", text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest." },
  { ref: "John 16:33", text: "In the world ye shall have tribulation: but be of good cheer; I have overcome the world." },
  { ref: "John 15:13", text: "Greater love hath no man than this, that a man lay down his life for his friends." },
  { ref: "Romans 8:37", text: "Nay, in all these things we are more than conquerors through him that loved us." },
  { ref: "1 Corinthians 15:58", text: "Be ye stedfast, unmoveable, always abounding in the work of the Lord." },
  { ref: "Galatians 2:20", text: "I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me." },
  { ref: "Ephesians 4:1", text: "Walk worthy of the vocation wherewith ye are called." },
  { ref: "Philippians 3:14", text: "I press toward the mark for the prize of the high calling of God in Christ Jesus." },
  { ref: "Philippians 4:6", text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God." },
  { ref: "Colossians 3:2", text: "Set your affection on things above, not on things on the earth." },
  { ref: "1 Thessalonians 5:11", text: "Wherefore comfort yourselves together, and edify one another, even as also ye do." },
  { ref: "Hebrews 10:24", text: "And let us consider one another to provoke unto love and to good works." },
  { ref: "Hebrews 10:25", text: "Not forsaking the assembling of ourselves together; but exhorting one another." },
  { ref: "Hebrews 11:1", text: "Now faith is the substance of things hoped for, the evidence of things not seen." },
  { ref: "Hebrews 13:6", text: "The Lord is my helper, and I will not fear what man shall do unto me." },
  { ref: "James 1:2-3", text: "Count it all joy when ye fall into divers temptations; knowing this, that the trying of your faith worketh patience." },
  { ref: "James 4:7", text: "Submit yourselves therefore to God. Resist the devil, and he will flee from you." },
  { ref: "1 Peter 2:9", text: "But ye are a chosen generation, a royal priesthood, an holy nation, a peculiar people." },
  { ref: "1 John 5:4", text: "For whatsoever is born of God overcometh the world: and this is the victory that overcometh the world, even our faith." },
  { ref: "Revelation 3:21", text: "To him that overcometh will I grant to sit with me in my throne." },
  { ref: "Psalm 19:14", text: "Let the words of my mouth, and the meditation of my heart, be acceptable in thy sight, O LORD, my strength, and my redeemer." },
  { ref: "Psalm 28:7", text: "The LORD is my strength and my shield; my heart trusted in him, and I am helped." },
  { ref: "Psalm 34:1", text: "I will bless the LORD at all times: his praise shall continually be in my mouth." },
  { ref: "Psalm 37:23", text: "The steps of a good man are ordered by the LORD: and he delighteth in his way." },
  { ref: "Psalm 51:10", text: "Create in me a clean heart, O God; and renew a right spirit within me." },
  { ref: "Psalm 91:1", text: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty." },
  { ref: "Psalm 121:1-2", text: "I will lift up mine eyes unto the hills, from whence cometh my help. My help cometh from the LORD." },
  { ref: "Proverbs 1:7", text: "The fear of the LORD is the beginning of knowledge." },
  { ref: "Proverbs 10:4", text: "He becometh poor that dealeth with a slack hand: but the hand of the diligent maketh rich." },
  { ref: "Proverbs 12:1", text: "Whoso loveth instruction loveth knowledge: but he that hateth reproof is brutish." },
  { ref: "Proverbs 22:29", text: "Seest thou a man diligent in his business? he shall stand before kings." },
  { ref: "Proverbs 28:1", text: "The righteous are bold as a lion." },
  { ref: "Isaiah 26:3", text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee." },
  { ref: "Isaiah 54:17", text: "No weapon that is formed against thee shall prosper." },
  { ref: "Matthew 7:7", text: "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you." },
  { ref: "Matthew 17:20", text: "If ye have faith as a grain of mustard seed, ye shall say unto this mountain, Remove hence to yonder place; and it shall remove." },
  { ref: "Luke 9:23", text: "If any man will come after me, let him deny himself, and take up his cross daily, and follow me." },
  { ref: "John 14:6", text: "I am the way, the truth, and the life: no man cometh unto the Father, but by me." },
  { ref: "Acts 20:24", text: "But none of these things move me, neither count I my life dear unto myself, so that I might finish my course with joy." },
  { ref: "Romans 12:11", text: "Not slothful in business; fervent in spirit; serving the Lord." },
  { ref: "Romans 15:1", text: "We then that are strong ought to bear the infirmities of the weak." },
  { ref: "1 Corinthians 10:13", text: "God is faithful, who will not suffer you to be tempted above that ye are able." },
  { ref: "1 Corinthians 13:11", text: "When I became a man, I put away childish things." },
  { ref: "2 Corinthians 5:7", text: "For we walk by faith, not by sight." },
  { ref: "Galatians 5:1", text: "Stand fast therefore in the liberty wherewith Christ hath made us free." },
  { ref: "Galatians 6:2", text: "Bear ye one another's burdens, and so fulfil the law of Christ." },
  { ref: "Ephesians 6:11", text: "Put on the whole armour of God, that ye may be able to stand against the wiles of the devil." },
  { ref: "Philippians 1:6", text: "He which hath begun a good work in you will perform it until the day of Jesus Christ." },
  { ref: "Philippians 4:8", text: "Whatsoever things are true, honest, just, pure, lovely, of good report; think on these things." },
  { ref: "Colossians 1:11", text: "Strengthened with all might, according to his glorious power, unto all patience and longsuffering with joyfulness." },
  { ref: "2 Thessalonians 3:13", text: "But ye, brethren, be not weary in well doing." },
  { ref: "1 Timothy 4:12", text: "Be thou an example of the believers, in word, in conversation, in charity, in spirit, in faith, in purity." },
  { ref: "Titus 2:7", text: "In all things shewing thyself a pattern of good works." },
  { ref: "Hebrews 4:16", text: "Let us therefore come boldly unto the throne of grace, that we may obtain mercy, and find grace to help in time of need." },
  { ref: "Hebrews 11:6", text: "But without faith it is impossible to please him: for he that cometh to God must believe that he is." },
  { ref: "James 2:17", text: "Even so faith, if it hath not works, is dead, being alone." },
  { ref: "1 Peter 4:10", text: "As every man hath received the gift, even so minister the same one to another." },
  { ref: "1 Peter 5:6", text: "Humble yourselves therefore under the mighty hand of God, that he may exalt you in due time." },
  { ref: "1 John 4:4", text: "Greater is he that is in you, than he that is in the world." },
  { ref: "Jude 1:20", text: "But ye, beloved, building up yourselves on your most holy faith, praying in the Holy Ghost." },
  { ref: "Psalm 30:5", text: "Weeping may endure for a night, but joy cometh in the morning." },
  { ref: "Psalm 55:22", text: "Cast thy burden upon the LORD, and he shall sustain thee." },
  { ref: "Psalm 90:17", text: "Let the beauty of the LORD our God be upon us: and establish thou the work of our hands." },
  { ref: "Proverbs 11:14", text: "In the multitude of counsellors there is safety." },
  { ref: "Proverbs 15:22", text: "Without counsel purposes are disappointed: but in the multitude of counsellors they are established." },
  { ref: "Proverbs 20:7", text: "The just man walketh in his integrity: his children are blessed after him." },
  { ref: "Isaiah 43:2", text: "When thou passest through the waters, I will be with thee; and through the rivers, they shall not overflow thee." },
  { ref: "Matthew 5:6", text: "Blessed are they which do hunger and thirst after righteousness: for they shall be filled." },
  { ref: "Matthew 5:16", text: "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven." },
  { ref: "Luke 6:31", text: "And as ye would that men should do to you, do ye also to them likewise." },
  { ref: "John 13:34", text: "A new commandment I give unto you, That ye love one another; as I have loved you." },
  { ref: "Romans 8:28", text: "And we know that all things work together for good to them that love God." },
  { ref: "1 Corinthians 13:4", text: "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up." },
  { ref: "2 Corinthians 9:7", text: "God loveth a cheerful giver." },
  { ref: "Galatians 5:22-23", text: "The fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, meekness, temperance." },
  { ref: "Ephesians 4:32", text: "Be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you." },
  { ref: "Philippians 2:3", text: "Let nothing be done through strife or vainglory; but in lowliness of mind let each esteem other better than themselves." },
  { ref: "Colossians 3:12", text: "Put on therefore, as the elect of God, holy and beloved, bowels of mercies, kindness, humbleness of mind, meekness, longsuffering." },
  { ref: "Psalm 112:7", text: "He shall not be afraid of evil tidings: his heart is fixed, trusting in the LORD." },
  { ref: "Proverbs 3:6", text: "In all thy ways acknowledge him, and he shall direct thy paths." },
  { ref: "Isaiah 6:8", text: "Then said I, Here am I; send me." },
  { ref: "Matthew 28:19", text: "Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost." },
  { ref: "Romans 1:16", text: "For I am not ashamed of the gospel of Christ: for it is the power of God unto salvation." },
];
