-- Deep fitness library: exercises (imported from the public-domain free-exercise-db)
-- + user routines (generated or custom) + their exercises.

create table if not exists public.exercises (
  id                text primary key,         -- slug id from the dataset
  name              text not null,
  level             text,                     -- beginner | intermediate | expert
  force             text,                     -- push | pull | static
  mechanic          text,                     -- compound | isolation
  equipment         text,                     -- body only | dumbbell | barbell | machine | ...
  category          text,                     -- strength | stretching | cardio | ...
  primary_muscles   text[] not null default '{}',
  secondary_muscles text[] not null default '{}',
  instructions      text[] not null default '{}',
  image_url         text,
  video_url         text,
  created_at        timestamptz not null default now()
);
create index if not exists exercises_equipment_idx on public.exercises (equipment);
create index if not exists exercises_category_idx on public.exercises (category);

alter table public.exercises enable row level security;
drop policy if exists exercises_read on public.exercises;
create policy exercises_read on public.exercises for select using (true);
drop policy if exists exercises_admin on public.exercises;
create policy exercises_admin on public.exercises for all using (public.is_admin()) with check (public.is_admin());

create table if not exists public.routines (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null,
  name       text not null,
  focus      text,                            -- e.g. Full Body, Upper, Push, Legs
  generated  boolean not null default false,  -- generated by the program builder vs custom
  sort       int not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists routines_user_idx on public.routines (user_id, sort);
alter table public.routines enable row level security;
drop policy if exists routines_owner on public.routines;
create policy routines_owner on public.routines for all using (user_id = auth.uid()) with check (user_id = auth.uid());

create table if not exists public.routine_exercises (
  id          uuid primary key default gen_random_uuid(),
  routine_id  uuid not null references public.routines (id) on delete cascade,
  exercise_id text not null references public.exercises (id),
  sort        int not null default 0,
  sets        int not null default 3,
  reps        text not null default '10',     -- "10", "8-12", "30s"
  rest        int not null default 60
);
create index if not exists routine_ex_routine_idx on public.routine_exercises (routine_id, sort);
alter table public.routine_exercises enable row level security;
drop policy if exists routine_ex_owner on public.routine_exercises;
create policy routine_ex_owner on public.routine_exercises for all
  using (exists (select 1 from routines r where r.id = routine_id and r.user_id = auth.uid()))
  with check (exists (select 1 from routines r where r.id = routine_id and r.user_id = auth.uid()));
